development:
  adapter: async

test:
  adapter: test

production:
  adapter: async # TEMPORARY FIX
  # adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # channel_prefix: server_production
