# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tsh-qc/./incorrect 5 (crumpled).jpeg', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tsh-qc/./incorrect 5 (crumpled).jpeg']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '2022-07-27r0', '--image', 'gcr.io/tsh-qc/./incorrect 5 (crumpled).jpeg', '--region', 'asia-southeast1']
images:
- gcr.io/tsh-qc/./incorrect 5 (crumpled).jpeg