steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/tsh-labels/dynostic-ai-img", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/tsh-labels/dynostic-ai-img"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "dynostic-ai",
        "--image",
        "gcr.io/tsh-labels/dynostic-ai-img",
        "--region",
        "asia-southeast1",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/tsh-labels/dynostic-ai-img
timeout: 900s
